import "./globals.css";
import RootStyleRegistry from "../utils/emotion";
import DarkLightTheme from "@/theme/DarkLightTheme";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageContainer from "@/components/PageContainer";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html>
      <head></head>
      <body>
        <DarkLightTheme>
          <RootStyleRegistry>
            <Providers>
              <Navbar />
              <PageContainer>{children}</PageContainer>
              <Footer />
            </Providers>
          </RootStyleRegistry>
        </DarkLightTheme>
      </body>
    </html>
  );
}
